[package]
name = "rusty-blockchain"
version = "0.1.0"
authors = ["Matt Witkowski"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
crypto-hash = "0.3.4"